[base]
env = "dev"
enable_api = true

[debug_test_case]
enable_reruns = true
test_case_name = ""

[test_lanes.api]
dev = [
  { name = "dummyjson_consistency", user = "client01", jobs = [
    [
      "./test/api/test_dummyjson_users.py",
    ],
  ] },
  { name = "dummyjson_carts", user = "client02", jobs = [
    [
      "./test/api/test_dummyjson_carts.py",
    ],
  ] },
]
prod = [
  { name = "dummyjson_consistency", user = "client01", jobs = [
    [
      "./test/api/test_dummyjson_users.py",
    ],
  ] },
  { name = "dummyjson_carts", user = "client02", jobs = [
    [
      "./test/api/test_dummyjson_carts.py",
    ],
  ] },
]
