[base]
env = "dev"
enable_api = true

[debug_test_case]
enable_reruns = true
test_case_name = ""

[test_lanes.api]
dev = [
  { name = "login", user = "client01", jobs = [
    [
      "./test/api/test_login.py",
    ],
  ] },
  { name = "profile", user = "client02", jobs = [
    [
      "./test/api/test_profile.py",
    ],
  ] },
]
prod = [
  { name = "login", user = "client01", jobs = [
    [
      "./test/api/test_login.py",
    ],
  ] },
]
